USE [master]
GO

/****** Object:  Database [CashRecieptForInsurance]    Script Date: 4/27/2017 4:26:50 PM ******/
CREATE DATABASE [CashRecieptForInsurance]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CashRecieptForInsurance', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\CashRecieptForInsurance.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CashRecieptForInsurance_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\CashRecieptForInsurance_log.ldf' , SIZE = 784KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CashRecieptForInsurance] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CashRecieptForInsurance].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CashRecieptForInsurance] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CashRecieptForInsurance] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CashRecieptForInsurance] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CashRecieptForInsurance] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CashRecieptForInsurance] SET ARITHABORT OFF 
GO

ALTER DATABASE [CashRecieptForInsurance] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [CashRecieptForInsurance] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [CashRecieptForInsurance] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CashRecieptForInsurance] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CashRecieptForInsurance] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CashRecieptForInsurance] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CashRecieptForInsurance] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CashRecieptForInsurance] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CashRecieptForInsurance] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CashRecieptForInsurance] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CashRecieptForInsurance] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CashRecieptForInsurance] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CashRecieptForInsurance] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CashRecieptForInsurance] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CashRecieptForInsurance] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CashRecieptForInsurance] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CashRecieptForInsurance] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CashRecieptForInsurance] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CashRecieptForInsurance] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CashRecieptForInsurance] SET  MULTI_USER 
GO

ALTER DATABASE [CashRecieptForInsurance] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CashRecieptForInsurance] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CashRecieptForInsurance] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CashRecieptForInsurance] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CashRecieptForInsurance] SET  READ_WRITE 
GO

